/**
 * @file types/index.ts
 * @description Shared type definitions for the TribeAI application.
 */

/**
 * Enum representing the type of message sender.
 */
export enum MessageType {
  /** Message sent by the user */
  User = 'user',
  /** Message generated by the AI */
  AI = 'ai',
}

/**
 * Represents a chat message in the conversation.
 */
export interface ForumResult {
  title: string
  link: string
  snippet: string
  username: string
  createdAt?: string
  score?: number
}

export interface PostSuggestion {
  title: string
  content: string
  tag: string
  tagName?: string
  link: string
}

export interface Message {
  /** Unique identifier for the message */
  id: string
  /** The type of message (user or AI) */
  type: MessageType
  /** The text content of the message */
  content: string
  /** When the message was created */
  timestamp: Date
  /** Optional post suggestion */
  suggestion?: PostSuggestion
  /** Optional forum results from RAG */
  forumResults?: ForumResult[]
}
