/**
 * @file types/index.ts
 * @description Shared type definitions for the TribeAI application.
 */

/**
 * Enum representing the type of message sender.
 */
export enum MessageType {
  /** Message sent by the user */
  User = 'user',
  /** Message generated by the AI */
  AI = 'ai',
}

/**
 * Represents a chat message in the conversation.
 */
export interface Message {
  /** Unique identifier for the message */
  id: string
  /** The type of message (user or AI) */
  type: MessageType
  /** The text content of the message */
  content: string
  /** When the message was created */
  timestamp: Date
}
